version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
      - VITE_VAPI_PUBLIC_KEY=${VITE_VAPI_PUBLIC_KEY}
      - VITE_VAPI_WORKFLOW_ID=${VITE_VAPI_WORKFLOW_ID}
      - VITE_VAPI_VIDEO_PUBLIC_KEY=${VITE_VAPI_VIDEO_PUBLIC_KEY}
      - VITE_VAPI_VIDEO_WORKFLOW_ID=${VITE_VAPI_VIDEO_WORKFLOW_ID}
      - VITE_VAPI_VIDEO_ASSISTANT_ID=${VITE_VAPI_VIDEO_ASSISTANT_ID}
      - VITE_OPENROUTER_API_KEY=${VITE_OPENROUTER_API_KEY}
    depends_on:
      - backend

  backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - MONGODB_URI=mongodb://mongo:27017/vedit
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: