[phases.setup]
nixPkgs = ["nodejs", "npm", "ffmpeg"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["chmod +x railway-build.sh && ./railway-build.sh"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
