[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install", "cd server && npm install"]

[phases.build]
cmds = ["echo 'Backend build complete'"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
