providers = ["node"]

[phases.setup]
nixpkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --omit=dev", "cd server && npm ci --omit=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node start-railway-fixed.cjs"

[variables]
NODE_ENV = "production"
