[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build:frontend"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "8080"
