providers = ["node"]

[phases.install]
cmds = ["npm ci --omit=dev", "cd server && npm ci --omit=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
