providers = ["node"]

[phases.install]
cmds = ["npm ci --omit=dev --no-audit --silent", "cd server && npm ci --omit=dev --no-audit --silent"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_LOGLEVEL = "error"
NPM_CONFIG_PROGRESS = "false"
NPM_CONFIG_AUDIT_LEVEL = "moderate"
